# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=85L)),
                ('artist_pic', models.ImageField(blank=True, null=True, upload_to=general.models.artist_picture_path)),
            ],
        ),
    ]
