# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=85L)),
                ('item_pic', models.ImageField(blank=True, null=True, upload_to=general.models.item_picture_path)),
            ],
        ),
    ]
