# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
